stages:
  - build
  - deploy

variables:
  REVISION: "4"

.build_template: &build_definition
  stage: build
  image: ventosus/arm-none-eabi
  before_script:
    - export PATH="/opt/x86_64-linux-gnu/bin:${PATH}"
    - git submodule update --init
  script:
    - make clean
    - make dfu
    - mkdir "chimaera_$(cat VERSION)-${REVISION}"
    - cp "build/chimaera_S${SENSORS}-$(cat VERSION)-${REVISION}.dfu" "chimaera_$(cat VERSION)-${REVISION}/."
  artifacts:
    name: "chimaera_S${SENSORS}-$(cat VERSION)-${REVISION}"
    paths:
      - "chimaera_$(cat VERSION)-${REVISION}"

# building in docker
S16:
  variables:
    SENSORS: "16"
  <<: *build_definition

S32:
  variables:
    SENSORS: "32"
  <<: *build_definition

S48:
  variables:
    SENSORS: "48"
  <<: *build_definition

S64:
  variables:
    SENSORS: "64"
  <<: *build_definition

S80:
  variables:
    SENSORS: "80"
  <<: *build_definition

S96:
  variables:
    SENSORS: "96"
  <<: *build_definition

S112:
  variables:
    SENSORS: "112"
  <<: *build_definition

S128:
  variables:
    SENSORS: "128"
  <<: *build_definition

S144:
  variables:
    SENSORS: "144"
  <<: *build_definition

S160:
  variables:
    SENSORS: "160"
  <<: *build_definition

pack:
  stage: deploy
  script:
    - echo 'packing up...'
  artifacts:
    name: "chimaera_$(cat VERSION)-${REVISION}"
    paths:
      - "chimaera_$(cat VERSION)-${REVISION}"
