language:
 - cpp
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get -q update
install:
 - sudo apt-get install -y --force-yes gcc-arm-none-eabi
script:
 - make
env:
 - SENSORS=16
 - SENSORS=32
 - SENSORS=48
 - SENSORS=64
 - SENSORS=80
 - SENSORS=96
 - SENSORS=112
 - SENSORS=128
 - SENSORS=144
 - SENSORS=160
